config/routes.rb
Rails.application.routes.draw do
  resources :redirect_rules
  root to: 'redirect_rules#index'
  get '*path', to: 'application#transfer', format: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/redirect_rule.rb
class RedirectRule < ApplicationRecord
  validates_presence_of :source, message: 'Please provide a valid source.'
  validates_presence_of :destination, message: 'Please provide a destination.'

  # Returns the destination for a given source URL
  #
  # @param source_url [String] The source URL
  # @return [String] The destination URL if a match is found
  # @return [nil] When no match is found
  def self.redirect(source_url)
    conditions = "(redirect_rules.regex = false AND LOWER(redirect_rules.source) = LOWER('#{source_url}')) OR (redirect_rules.regex = true AND '#{source_url}' ~* redirect_rules.source)"
    redirect_rule = self.where(conditions).first
    if redirect_rule.present?
      if redirect_rule.regex?
        match_string = source_url.gsub(/#{redirect_rule.source.split('[')[0]}/, '')
        redirect_rule.destination.gsub('{match}', match_string)
      else
        redirect_rule.destination
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def transfer
    source_url, request_type = set_source_and_type
    redirect_url = RedirectRule.redirect(source_url)
    if redirect_url.present?
      request_type == 'transfer' ? (redirect_to redirect_url) : (render json: { destination: redirect_url })
    else
      request_type == 'transfer' ? (render plain: '404 Not found', status: 404) : (render json: { error: 'not_found' }, status: 404)
    end
  end

  private

  def set_source_and_type
    if request.fullpath.match(/\A\/(transfer|api)\?source=/) # When source has payload
      source_url = request.fullpath.gsub(/\A\/(transfer|api)\?source=/, '')
      request_type = request.fullpath.match(/\A\/transfer\?source=/) ? 'transfer' : 'api'
    else # Local Request
      source_url = request.original_url
      request_type = 'transfer'
    end
    [source_url, request_type]
  end

end

app/controllers/redirect_rules_controller.rb
class RedirectRulesController < ApplicationController
  before_action :set_redirect_rule, only: [:show, :edit, :update, :destroy]

  # GET /redirect_rules
  # GET /redirect_rules.json
  def index
    @redirect_rules = RedirectRule.all
  end

  # GET /redirect_rules/1
  # GET /redirect_rules/1.json
  def show
  end

  # GET /redirect_rules/new
  def new
    @redirect_rule = RedirectRule.new
  end

  # GET /redirect_rules/1/edit
  def edit
  end

  # POST /redirect_rules
  # POST /redirect_rules.json
  def create
    @redirect_rule = RedirectRule.new(redirect_rule_params)

    respond_to do |format|
      if @redirect_rule.save
        format.html { redirect_to @redirect_rule, notice: 'Redirect rule was successfully created.' }
        format.json { render :show, status: :created, location: @redirect_rule }
      else
        format.html { render :new }
        format.json { render json: @redirect_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redirect_rules/1
  # PATCH/PUT /redirect_rules/1.json
  def update
    respond_to do |format|
      if @redirect_rule.update(redirect_rule_params)
        format.html { redirect_to @redirect_rule, notice: 'Redirect rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @redirect_rule }
      else
        format.html { render :edit }
        format.json { render json: @redirect_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redirect_rules/1
  # DELETE /redirect_rules/1.json
  def destroy
    @redirect_rule.destroy
    respond_to do |format|
      format.html { redirect_to redirect_rules_url, notice: 'Redirect rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redirect_rule
      @redirect_rule = RedirectRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def redirect_rule_params
      params.require(:redirect_rule).permit(:source, :regex, :destination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Zigzag" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Zigzag</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/redirect_rules/_form.html.erb
<%= simple_form_for @redirect_rule, :html => { :class => 'form-horizontal', onsubmit: 'validateForm()'} do |f| %>
  <%= f.input :source, required: true %>
  <%= f.input :regex %>
  <%= f.input :destination, required: true %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                redirect_rules_path, :class => 'btn btn-default' %>
<% end %>

app/views/redirect_rules/edit.html.erb
<%- model_class = RedirectRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/redirect_rules/index.html.erb
<%- model_class = RedirectRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<p>There are 3 ways to use it;</p>
<ul>
  <li>Redirection: <strong>http://localhost:3000/transfer?source=[Your source URL]</strong>. The request will be redirected.</li>
  <li>API: <strong>http://localhost:3000/api?source=[Your source URL]</strong>. The request will render a JSON response.</li>
  <li>Relative Redirection: <strong>http://localhost:3000/[Your relative source URL]</strong>. The request will be redirected if entry is present for host.</li>
</ul>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%= model_class.human_attribute_name(:regex) %></th>
      <th><%= model_class.human_attribute_name(:destination) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @redirect_rules.each do |redirect_rule| %>
      <tr>
        <td><%= link_to redirect_rule.id, redirect_rule_path(redirect_rule) %></td>
        <td><%= redirect_rule.source %></td>
        <td><%= redirect_rule.regex %></td>
        <td><%= redirect_rule.destination %></td>
        <td><%=l redirect_rule.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      redirect_rule_path(redirect_rule), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_redirect_rule_path(redirect_rule), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      redirect_rule_path(redirect_rule),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_redirect_rule_path,
            :class => 'btn btn-primary' %>

app/views/redirect_rules/new.html.erb
<%- model_class = RedirectRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  <h4>Source allows RegExp. Please make sure you escape the RegExp.</h4>
  <p>You may use wildcards to use single rule to slay multiple items. Use {match} keyword in destination to make replacements.</p>
  <p>If you want to allow query string, don't add $ to end of your Regexp</p>
  <h2>Example</h2>
  <p><strong>Source: </strong>http:\/\/written.rwdev.io\/[0-9]*$</p>
  <p><strong>Regex: </strong>Checked</p>
  <p><strong>Destination: </strong>http://ios.rwdev.io/articles/{match}</p>
  <p><em>In the above example, an URL like http://written.rwdev.io/2323 will lead to http://ios.rwdev.io/articles/2323</em></p>
  <h2>Usage</h2>
</div>
<%= render :partial => 'form' %>

app/views/redirect_rules/show.html.erb
<%- model_class = RedirectRule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @redirect_rule.source %></dd>
  <dt><strong><%= model_class.human_attribute_name(:regex) %>:</strong></dt>
  <dd><%= @redirect_rule.regex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:destination) %>:</strong></dt>
  <dd><%= @redirect_rule.destination %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              redirect_rules_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_redirect_rule_path(@redirect_rule), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              redirect_rule_path(@redirect_rule),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>